{
 "title": "CASPER VALIDATOR  Mainnet",
 "description": "Work in progress",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Explorer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CSPR Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cryptocurrency_cspr_price{job=\"crypto-price\"}"
    }
   ]
  },
  {
   "title": "Total Self Staked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "casper_validator_self_staked_amount{job=\"casper\"}"
    }
   ]
  },
  {
   "title": "Total Staked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "casper_validator_total_staked_amount{job=\"casper\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "casper_validator_is_active{job=\"casper\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "casper_validator_should_be_upgraded{job=\"casper\"}",
     "legendFormat": "{{ next_version }}"
    }
   ]
  },
  {
   "title": "TOP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "casper_validator_position{job=\"casper\"}"
    }
   ]
  },
  {
   "title": "Current Era",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(casper_validator_block_local_era{job=\"casper\"})"
    }
   ]
  },
  {
   "title": "APR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "casper_validator_current_apr{job=\"casper\"}"
    }
   ]
  },
  {
   "title": "LXC CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT mean(\"cpu\") FROM \"cpustat\" WHERE (\"object\" = 'lxc') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "object", "operator": "=", "value": "lxc" },
      { "condition": "AND", "key": "nodename", "operator": "=", "value": "pve-node-2" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "cspr-validator" }
     ]
    }
   ]
  },
  {
   "title": "LXC Used Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(mem) FROM \"system\" WHERE (\"object\" = 'lxc') AND (\"nodename\" = 'pve-node-2') AND $timeFilter AND (\"host\" = 'cspr-validator')",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/ 1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" },
      { "condition": "AND", "key": "nodename", "operator": "=", "value": "pve-node-2" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "cspr-validator" }
     ]
    }
   ]
  },
  {
   "title": "LXC Disk Using",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "query": "SELECT last(mem) FROM \"system\" WHERE (\"object\" = 'lxc') AND (\"nodename\" = 'pve-node-2') AND $timeFilter AND (\"host\" = 'cspr-validator')",
     "select": [
      [
       { "params": [ "disk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/ 1073741824" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "object", "operator": "=", "value": "lxc" },
      { "condition": "AND", "key": "nodename", "operator": "=", "value": "pve-node-2" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "cspr-validator" }
     ]
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "casper_validator_peers{job=\"casper\"}"
    }
   ]
  },
  {
   "title": "Current Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(casper_validator_block_local_height{job=\"casper\"})"
    }
   ]
  },
  {
   "title": "Commission Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "casper_validator_delegation_rate{job=\"casper\"}"
    }
   ]
  },
  {
   "title": "Last Rewards",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(era_id)(casper_validator_era_rewards{job=\"casper\"})",
     "legendFormat": "{{era_id}}"
    }
   ]
  },
  { "title": "Staked Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Self Staked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "casper_validator_self_staked_amount{job=\"casper\"}",
     "legendFormat": "Self Staked"
    }
   ]
  },
  {
   "title": "Total Staked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "casper_validator_total_staked_amount{job=\"casper\"}",
     "legendFormat": "Total Staked"
    }
   ]
  },
  {
   "title": "Casper Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cryptocurrency_cspr_price{job=\"crypto-price\"}",
     "legendFormat": "CSPR"
    }
   ]
  },
  { "title": "Node Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "casper_validator_build_version{job=\"casper\"}"
    }
   ]
  },
  {
   "title": "Alert Utility ( for setting alerts )",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "Validator State Alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Validator Status" }
   ],
   "targets": [
    {
     "expr": "casper_validator_is_active{job=\"casper\"}",
     "legendFormat": "Validator Status"
    }
   ]
  },
  {
   "title": "Is Upgrade Staged",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Upgrade Staged" }
   ],
   "targets": [
    {
     "expr": "casper_validator_should_be_upgraded{job=\"casper\"}"
    }
   ]
  }
 ]
}